apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cashback-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cashback
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 10

  