apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-dep
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - image: brunodixini/account-service:latest
          name: account
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
      

      