apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: card-dep
  name: card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
        - image: brunodixini/card-service:latest
          name: card
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m