apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cashback-dep
  name: cashback
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cashback
  template:
    metadata:
      labels:
        app: cashback
    spec:
      containers:
        - image: brunodixini/cashback:1.0
          name: cashback
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 100m
      

      