apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: credito-dep
  name: credito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credito
  template:
    metadata:
      labels:
        app: credito
    spec:
      containers:
        - image: brunodixini/credito:1.0
          name: credito
          ports:
          - containerPort: 8080