apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer-dep
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - image: brunodixini/customer-service:latest
          name: customer
          ports:
            - containerPort: 8080