apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loan-dep
  name: loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - image: brunodixini/loan-service:latest
          name: loan
          ports:
            - containerPort: 8080