micronaut:
  application:
    name: crudmicronaut
  server:
    port: 8081

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/postgres`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    entity-scan:
      packages: 'com.inter.domain.model'